-- SELFIE AI™ Data Migration for Supabase

-- User Profiles
INSERT INTO user_profiles (user_id, brand_mission, ideal_audience, brand_values, key_phrases, hashtags, visual_aesthetic, content_focus, tone_voice, industry, experience_level, main_goals, transformation_story, brand_voice, aesthetic_tone, offer, visibility_goals, is_complete) VALUES ('1', 'HElping women build personal brand ', 'Women starting over after divorce', NULL, 'Lets do this together shall we...', '#selfie', 'Moody & Modern', ARRAY['Personal Stories','Business Strategy','Fashion & Beauty','Motivation & Mindset'], 'Warm & Friendly', 'coaching and social media', NULL, 'Grow on social media', NULL, NULL, NULL, NULL, NULL, true) ON CONFLICT (user_id) DO UPDATE SET brand_mission = EXCLUDED.brand_mission, ideal_audience = EXCLUDED.ideal_audience, updated_at = NOW();
INSERT INTO user_profiles (user_id, brand_mission, ideal_audience, brand_values, key_phrases, hashtags, visual_aesthetic, content_focus, tone_voice, industry, experience_level, main_goals, transformation_story, brand_voice, aesthetic_tone, offer, visibility_goals, is_complete) VALUES ('test-user-123', 'Empowering women entrepreneurs to build authentic personal brands', 'Female entrepreneurs aged 25-45 seeking brand clarity', 'Authenticity, Empowerment, Growth', 'authentic success, aligned action, purposeful growth', '#authenticbrand #femaleentrepreneur #businesscoach #mindsetmatters #purposefulbusiness', 'Luxury & Sophisticated', ARRAY['Personal Branding','Business Strategy','Mindset Coaching'], 'Inspirational & Motivating', 'Business Coaching', 'Established Creator', 'Scale to 6-figure coaching business', NULL, NULL, NULL, NULL, NULL, true) ON CONFLICT (user_id) DO UPDATE SET brand_mission = EXCLUDED.brand_mission, ideal_audience = EXCLUDED.ideal_audience, updated_at = NOW();
INSERT INTO user_profiles (user_id, brand_mission, ideal_audience, brand_values, key_phrases, hashtags, visual_aesthetic, content_focus, tone_voice, industry, experience_level, main_goals, transformation_story, brand_voice, aesthetic_tone, offer, visibility_goals, is_complete) VALUES ('personalization-test-user', 'Empowering creative women to build profitable online businesses', 'Female creatives and entrepreneurs aged 28-40', 'Creativity, Authenticity, Financial Freedom, Community', 'creative freedom, authentic business, profitable passion', '#creativebusiness #femalefounder #onlineentrepreneur #creativefreedom #profitablepassion', 'Clean & Professional', ARRAY['Personal Branding','Business Strategy','Creative Process','Financial Tips'], 'Bold & Confident', 'Creative Business Coaching', 'Established Creator', 'Scale to multi-six-figure business with team of 5', NULL, NULL, NULL, NULL, NULL, true) ON CONFLICT (user_id) DO UPDATE SET brand_mission = EXCLUDED.brand_mission, ideal_audience = EXCLUDED.ideal_audience, updated_at = NOW();
INSERT INTO user_profiles (user_id, brand_mission, ideal_audience, brand_values, key_phrases, hashtags, visual_aesthetic, content_focus, tone_voice, industry, experience_level, main_goals, transformation_story, brand_voice, aesthetic_tone, offer, visibility_goals, is_complete) VALUES ('ai-integration-test-user', 'Helping busy entrepreneurs build authentic personal brands that convert', 'Time-strapped business owners aged 30-50 seeking brand clarity', 'Efficiency, Authenticity, Results-Driven Growth', 'strategic efficiency, authentic leadership, premium results', '#businessstrategy #executivecoach #luxurybrand #authenticleadership #premiumconsulting', 'Luxury & Sophisticated', ARRAY['Business Strategy','Time Management','Personal Branding','Leadership'], 'Professional & Authoritative', 'Business Consulting', 'Established Creator', 'Launch premium consulting program and scale to 7-figures', NULL, NULL, NULL, NULL, NULL, true) ON CONFLICT (user_id) DO UPDATE SET brand_mission = EXCLUDED.brand_mission, ideal_audience = EXCLUDED.ideal_audience, updated_at = NOW();
INSERT INTO user_profiles (user_id, brand_mission, ideal_audience, brand_values, key_phrases, hashtags, visual_aesthetic, content_focus, tone_voice, industry, experience_level, main_goals, transformation_story, brand_voice, aesthetic_tone, offer, visibility_goals, is_complete) VALUES ('test-400-fix', 'Helping women start over after heartbreak', 'Women who have lost themselves in relationship and motherhood', NULL, 'Lets do this together shall we...', '#selfie,#startingover', 'Minimalistic & Clean', ARRAY['Personal Stories','Educational Content','Business Strategy'], 'Warm & Friendly', 'Coaching', NULL, 'Grow my Instagram', NULL, NULL, NULL, NULL, NULL, true) ON CONFLICT (user_id) DO UPDATE SET brand_mission = EXCLUDED.brand_mission, ideal_audience = EXCLUDED.ideal_audience, updated_at = NOW();

-- Users
INSERT INTO users (email, first_name, last_name, plan, profile_data) VALUES ('sandrajonna@gmail.com', 'Sandra', 'Sigurjonsdottir', 'pro', '{"name":"TestUser","goals":"help moms feel confident and strong","niche":"fitness coaching","offer":"28-day fitness program","story":"single mom transformation","audience":"busy moms"}'::jsonb) ON CONFLICT (email) DO UPDATE SET first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name;
INSERT INTO users (email, first_name, last_name, plan, profile_data) VALUES ('sandra@dibssocial.com', 'Sandra', 'Aamodt', 'free', NULL) ON CONFLICT (email) DO UPDATE SET first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name;
INSERT INTO users (email, first_name, last_name, plan, profile_data) VALUES ('sandra@selfieai.com', 'Sandra', 'Social', 'free', NULL) ON CONFLICT (email) DO UPDATE SET first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name;
INSERT INTO users (email, first_name, last_name, plan, profile_data) VALUES ('sandra_test_1748348627513@selfieai.com', 'Sandra', 'Social', 'free', NULL) ON CONFLICT (email) DO UPDATE SET first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name;
INSERT INTO users (email, first_name, last_name, plan, profile_data) VALUES ('sandra_test_1748348889320@selfieai.com', 'Sandra', 'Social', 'free', '{"niche":"helping women rebuild after heartbreak","offer":"personal branding coaching for major life transitions","story":"divorced single mom who rebuilt her life and grew to 120K followers","audience":"women going through divorce, career changes, and life rebuilds","firstName":"Sandra"}'::jsonb) ON CONFLICT (email) DO UPDATE SET first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name;
INSERT INTO users (email, first_name, last_name, plan, profile_data) VALUES ('sandra_test_1748349028546@selfieai.com', 'Sandra', 'Social', 'free', '{"niche":"helping women rebuild after heartbreak","offer":"personal branding coaching for major life transitions","story":"divorced single mom who rebuilt her life and grew to 120K followers","audience":"women going through divorce, career changes, and life rebuilds","firstName":"Sandra"}'::jsonb) ON CONFLICT (email) DO UPDATE SET first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name;
INSERT INTO users (email, first_name, last_name, plan, profile_data) VALUES ('sandra_test_1748349160085@selfieai.com', 'Sandra', 'Social', 'free', '{"niche":"helping women rebuild after heartbreak","offer":"personal branding coaching for major life transitions","story":"divorced single mom who rebuilt her life and grew to 120K followers","audience":"women going through divorce, career changes, and life rebuilds","firstName":"Sandra"}'::jsonb) ON CONFLICT (email) DO UPDATE SET first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name;
INSERT INTO users (email, first_name, last_name, plan, profile_data) VALUES ('sandra_test_1748349177291@selfieai.com', 'Sandra', 'Social', 'free', '{"niche":"helping women rebuild after heartbreak","offer":"personal branding coaching for major life transitions","story":"divorced single mom who rebuilt her life and grew to 120K followers","audience":"women going through divorce, career changes, and life rebuilds","firstName":"Sandra"}'::jsonb) ON CONFLICT (email) DO UPDATE SET first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name;
INSERT INTO users (email, first_name, last_name, plan, profile_data) VALUES ('sandra_test_1748349476887@selfieai.com', 'Sandra', 'Social', 'free', '{"niche":"helping women rebuild after heartbreak","offer":"personal branding coaching for major life transitions","story":"divorced single mom who rebuilt her life and grew to 120K followers","audience":"women going through divorce, career changes, and life rebuilds","firstName":"Sandra"}'::jsonb) ON CONFLICT (email) DO UPDATE SET first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name;
INSERT INTO users (email, first_name, last_name, plan, profile_data) VALUES ('sandra_test_1748349795857@selfieai.com', 'Sandra', 'Social', 'free', '{"niche":"helping women rebuild after heartbreak","offer":"personal branding coaching for major life transitions","story":"divorced single mom who rebuilt her life and grew to 120K followers","audience":"women going through divorce, career changes, and life rebuilds","firstName":"Sandra"}'::jsonb) ON CONFLICT (email) DO UPDATE SET first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name;
INSERT INTO users (email, first_name, last_name, plan, profile_data) VALUES ('sandra_test_1748349828730@selfieai.com', 'Sandra', 'Social', 'free', '{"niche":"helping women rebuild after heartbreak","offer":"personal branding coaching for major life transitions","story":"divorced single mom who rebuilt her life and grew to 120K followers","audience":"women going through divorce, career changes, and life rebuilds","firstName":"Sandra"}'::jsonb) ON CONFLICT (email) DO UPDATE SET first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name;
INSERT INTO users (email, first_name, last_name, plan, profile_data) VALUES ('ssa@ssasocial.com', 'Sandra', 'Aamodt', 'VIP', NULL) ON CONFLICT (email) DO UPDATE SET first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name;
